---
title: "Predicting Diabetes using Pima Indians Data Set"
author: "Aadil V"
output: html_document
---
```{r, results='hide', message=FALSE, warning=FALSE} 
library(neuralnet)
library(caret)
library(tidyverse)
library(mlbench)
library(e1071)
library(ranger)

```
```{r}
data(PimaIndiansDiabetes)
df <- PimaIndiansDiabetes
str(df)

## Plotting the outcomes of the response variables
ggplot(df, aes(diabetes, fill = factor(diabetes))) +
    geom_bar() +
    labs(title = "Diabetes Outcomes in the Pima Indians Dataset",
       x = "Diabetes Status", 
       y = "Count") +
  theme(plot.title = element_text(hjust = 0.5))

##Creating a binary variable for the response variable
df$binary <- ifelse(df$diabetes == "neg", 0, 1)
str(df)

```
```{r}
## Splitting the data into training and testing sets using caret's createDataPartition function.

rows <- createDataPartition(df$binary, times = 1, p = .7, list = FALSE)

train <- df[rows,]
test <- df[-rows,]

dim(train)
dim(test)
```
```{r}
## Fix overfitting and perfect accuracy on both train and test sets by removing diabetes column

train <- train[,-9]
test <- test[,-9]
str(train)


```

```{r}
## Building a random forest model
model <- train(as.factor(binary) ~ ., ## Train model predicting `binary` based on all other variables
               data = train, ## Use training data
               method = "ranger", ## Use random forest
               trControl = trainControl(method = "repeatedcv", number = 2, repeats = 2)) ## Use repeated cross validation with 2 folds and 2 repeats

model

```

```{r}
## Testing the model on the test set and building a confusion matrix where 0 represents  diabetes negative and 1 represents diabetes positive
pred_train <- predict(model, train)
pred_test <- predict(model, test)

pred_train

confusionMatrix(pred_train, as.factor(train$binary))
confusionMatrix(pred_test, as.factor(test$binary))

```
